# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: encryption.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    6,
    '',
    'encryption.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10\x65ncryption.proto\x12\nencryption\"\"\n\x0e\x45ncryptRequest\x12\x10\n\tplaintext\x18\x01 \x01(\t\"L\n\x0f\x45ncryptResponse\x12\x12\n\nciphertext\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"$\n\x0e\x44\x65\x63ryptRequest\x12\x12\n\nciphertext\x18\x01 \x01(\t\"J\n\x0f\x44\x65\x63ryptResponse\x12\x10\n\tplaintext\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\x9b\x01\n\x11\x45ncryptionService\x12\x42\n\x07\x45ncrypt\x12\x1a.encryption.EncryptRequest\x1a\x1b.encryption.EncryptResponse\x12\x42\n\x07\x44\x65\x63rypt\x12\x1a.encryption.DecryptRequest\x1a\x1b.encryption.DecryptResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'encryption_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
# @@protoc_insertion_point(module_scope)
